import { fullTraceLab as en } from '../../en/behind-ai/fullTraceLab';
import type { FullTraceLabContent } from '../../he/behind-ai/fullTraceLab';

const copy: Record<string, [string, string, string]> = {
    context: ['تجميع السياق', 'المنتج يجمع ما هو متاح الآن', 'التخزين ليس مدخل النموذج. يفصل المنتج بين السياق الحالي والتاريخ والذاكرة المحفوظة وسياسة الاحتفاظ؛ لا نحتاج ذاكرة هنا.'],
    'model-input': ['مدخل النموذج', 'يدخل إلى النموذج ما جُمع الآن فقط', 'هذه حزمة تعليمية مبسطة، وتختلف صيغة التنفيذ بين المنتجات.'],
    tokens: ['Tokens و IDs', 'يتحول النص إلى وحدات ثم معرفات', 'الوحدة ليست دائما كلمة، وID عنوان لا يحمل المعنى بذاته.'],
    representations: ['Embeddings', 'تتحول IDs إلى تمثيلات', 'تحول الطبقات المتجهات حسب السياق؛ ليست خريطة معنى ثابتة.'],
    'attention-context': ['Attention والنافذة', 'يوزن النموذج العلاقات في النافذة الحالية', 'Attention ديناميكي وليس ترتيبا دائما، والنافذة ليست كل ما خُزن.'],
    generation: ['من logits إلى التوليد', 'ينتج Softmax توزيعا ويختار decoding', 'logits ‏2.0/1.0/0.0 تعطي ‏0.665/0.245/0.090؛ تضاف الوحدة المختارة وتتكرر الحلقة حتى شرط توقف.'],
    'grounding-choice': ['الخطر والإسناد', 'يقرر النظام هل يحتاج دليلا حديثا', 'قد يبدو النص مقنعا بلا دليل. حالة الطرد الحالية تحتاج أداة، بينما قد يتخطاها سؤال معرفة بسيط.'],
    'agent-tool': ['Agent والأداة', 'الـ Agent نظام يحيط بالنموذج', 'قد يقترح النموذج استدعاء منظما، لكن التطبيق يقرر الأداة وحدودها ومحاولة إعادة واحدة.'],
    authorization: ['التفويض', 'يفحص التطبيق authorization والسياسة', 'قراءة التتبع مسموحة، والإرسال يحتاج approval منفصلا؛ الثقة لا تتجاوز أي فحص.'],
    'tool-result': ['تنفيذ الأداة', 'يعيد النظام الخارجي نتيجة قابلة للملاحظة', 'الطرد 123456789 متأخر ولا يوجد تاريخ مؤكد؛ وقد يبقى الدليل الخارجي ناقصا.'],
    'draft-check': ['المسودة والفحص', 'تخضع المسودة المسندة لفحص غير معصوم', 'لا يثبت self-check الحقيقة: لا تاريخ مخترع ولا ادعاء إرسال وعدم اليقين ظاهر.'],
    approval: ['موافقة بشرية', 'الإرسال يحتاج تأكيدا صريحا', 'الافتراضي عدم الإرسال. التفويض النظامي ليس موافقة بشرية.'],
    verification: ['التنفيذ والتحقق', 'تُقارن النتيجة المرصودة بهدف المستخدم', 'نجاح استدعاء الأداة لا يعني دائما اكتمال المهمة، لذلك تعرض حالة نهائية صادقة.'],
    offline: ['التغذية الراجعة والتقييم', 'يحدث التحسين لاحقا وبشكل منفصل', 'لا تستخدم كل ملاحظة. يُختبر التحديث على حالات held-out منفصلة ولا يحدث تدريب فوري من محادثة واحدة.'],
};

export const fullTraceLab: FullTraceLabContent = {
    ...en, sectionTitle: 'طلب واحد، طبقات متعددة، نتيجة قابلة للتحقق', sectionIntro: 'تتبع طلب الطرد نفسه عبر السياق والنموذج والإسناد والـ Agent والضوابط والتنفيذ المحاكى والتحقق.', heading: 'المسار الكامل', promptLabel: 'طلب المستخدم', prompt: 'تحقق من الطرد 123456789، واكتب تحديثا للعميل، ولا ترسله دون موافقتي.', disclosure: 'هذه محاكاة تعليمية مكتوبة مسبقا، بلا اتصال أو إرسال حقيقي وبلا كشف سلسلة تفكير مخفية.', variabilityNote: 'ليس كل طلب يستخدم الذاكرة أو RAG أو الأدوات أو Agent أو الموافقة أو self-check أو التحسين اللاحق. قد تُتخطى المراحل أو تتكرر أو تتوقف مبكرا.', layerHeading: 'الطبقة النشطة',
    layers: { model: { label: 'Model internal', description: 'حساب داخل النموذج' }, product: { label: 'Application or product', description: 'تجميع وتنظيم وحالة مهمة' }, tool: { label: 'External system or tool', description: 'تكامل خارجي محدد' }, human: { label: 'Human control', description: 'قرار بشري صريح' }, offline: { label: 'Offline improvement process', description: 'عملية لاحقة منفصلة' } }, statusLabels: { required: 'المسار الرئيسي', optional: 'اختياري', skipped: 'متخطى هنا', repeated: 'قد يتكرر', stop: 'نقطة توقف' }, labels: { input: 'المدخل', process: 'التحويل أو القرار', output: 'المخرج', details: 'تفاصيل', branchReason: 'سبب الفرع', stopReason: 'سبب التوقف', stage: 'مرحلة', previous: 'السابق', next: 'التالي', reset: 'إعادة الضبط', selectStage: 'اختر مرحلة', progress: (c, t) => `الموضع ${c} من ${t} مع مسارات اختيارية` },
    stages: en.stages.map((s) => { const c = copy[s.id]; const localized = c ? { ...s, tab: c[0], title: c[1], refresher: c[2], input: c[2], process: c[2], output: c[2], facts: undefined, details: undefined, branchReason: undefined, stopReason: undefined } : s; if (s.id === 'tokens') localized.details = { label: 'مثال موجز', items: ['"تحقق" ← ID 4812', '"الطرد" ← ID 907', 'قد ينقسم الرقم إلى وحدات', 'لا يحمل ID المعنى بذاته'] }; if (s.id === 'representations') localized.details = { label: 'تمثيل موجز', items: ['4812 ← [0.2, −0.4, …]', '907 ← [0.7, 0.1, …]', 'تحول الطبقات المتجهات'] }; if (s.id === 'generation') localized.details = { label: 'المثال العددي الوحيد', items: ['‏2.0 / 1.0 / 0.0 هي logits', 'Softmax: 0.665 / 0.245 / 0.090', 'Softmax لا يختار', 'Decoding يختار وتتكرر الحلقة'] }; if (s.id === 'grounding-choice') localized.branchReason = 'تتغير الحالة بمرور الوقت، والاسترجاع يضيف دليلا ولا يغير المعلمات.'; if (s.id === 'approval') localized.stopReason = 'طلب المستخدم موافقة صريحة قبل الإرسال.'; if (s.id === 'verification') localized.branchReason = 'من دون موافقة يُتخطى التنفيذ.'; if (s.id === 'offline') localized.branchReason = 'هذا مسار offline منفصل.'; return localized; }),
    branches: { ...en.branches, title: 'استكشف فروع المحاكاة', intro: 'قد يستمر المسار أو يتخطى مرحلة أو يتوقف.', missingInfo: { label: 'رقم التتبع مفقود', outcome: 'نسأل المستخدم ولا نخترع.' }, knowledge: { label: 'سؤال معرفة بسيط', outcome: 'يمكن تخطي الأداة والموافقة.' }, toolNeeded: { label: 'الحالة الحالية', outcome: 'تحتاج أداة لأنها تتغير.' }, toolError: { label: 'محاكاة خطأ', first: 'فشلت المحاولة 1. بقي retry واحد.', retry: 'فشل retry ‏1 من 1.', exhausted: 'نفد الحد: الحالة failed.' }, approval: { ...en.branches.approval, title: 'موافقة تعليمية', pending: 'بانتظار القرار، لم يُرسل', deny: 'رفض الإرسال', approve: 'الموافقة على إرسال محاكى', denied: 'رُفضت الموافقة، لا تنفيذ.', approved: 'موافقة للمحاكاة فقط.', accepted: 'محاكاة accepted', rejected: 'محاكاة rejected', verifyAccepted: 'تم التحقق من accepted: نجاح محاكى.', verifyRejected: 'تم التحقق من rejected: failed.' }, restart: 'إعادة الفرع' }, sr: { stageGroup: 'اختيار مرحلة', stageDetail: 'تفاصيل المرحلة النشطة', branchGroup: 'اختيار فرع تعليمي' },
};
