import { fullTraceLab as en } from '../../en/behind-ai/fullTraceLab';
import type { FullTraceLabContent } from '../../he/behind-ai/fullTraceLab';

const stageCopy: Record<string, [string, string, string, string, string]> = {
    context: ['Ensamblaje de contexto', 'El producto reúne lo disponible ahora', 'La solicitud y el estado actual de la conversación.', 'Añade reglas relevantes y separa historial, memoria guardada y retención. La memoria es opcional; retención solo indica almacenamiento.', 'Solo entra el contexto actual ensamblado. Aquí no se recupera memoria ni existe un resultado previo.'],
    'model-input': ['Entrada del modelo', 'Solo el paquete ensamblado llega al modelo', 'Regla del sistema, objetivo, límites y datos seleccionados.', 'El producto crea una simplificación educativa estructurada; el formato varía por producto.', 'Objetivo: revisar 123456789. Límite: no enviar. Falta: estado y fecha. Fuentes: ninguna todavía.'],
    tokens: ['Tokens e IDs', 'El texto se convierte en tokens e identificadores', 'Un fragmento de la entrada.', 'El tokenizador separa piezas, que no siempre son palabras, y asigna un ID.', 'Los IDs son identificadores y no contienen significado por sí solos.'],
    representations: ['Embeddings', 'Los IDs se convierten en representaciones', 'La secuencia de IDs.', 'Los IDs se mapean a vectores y las capas transforman las representaciones según el contexto.', 'Representaciones contextuales, no un mapa semántico fijo.'],
    'attention-context': ['Attention y ventana', 'El modelo pondera relaciones en la ventana actual', 'Representaciones e información disponible ahora.', 'Attention es dinámico para este cálculo; la ventana no es todo lo almacenado.', 'Una representación actualizada para predecir el siguiente token.'],
    generation: ['De logits a generación', 'Softmax distribuye y decoding elige', 'La representación actualizada.', 'Logits 2.0/1.0/0.0 son puntuaciones. Softmax produce 0.665/0.245/0.090; decoding elige.', 'El token se añade y el ciclo se repite hasta una condición de parada.'],
    'grounding-choice': ['Riesgo y grounding', 'El sistema decide si necesita evidencia actual', 'Se pide el estado actual de un paquete.', 'Una respuesta plausible sin fuente no se usa aquí; una pregunta simple podría omitir herramientas.', 'Se solicita una propuesta estructurada de herramienta.'],
    'agent-tool': ['Agent y herramienta', 'El Agent es un sistema alrededor del modelo', 'Objetivo, restricciones, estado de tarea y propuesta tracking.lookup.', 'El modelo puede proponer; la aplicación decide disponibilidad y adecuación dentro de límites.', 'Herramienta e input estructurado para 123456789.'],
    authorization: ['Autorización', 'La aplicación comprueba autorización y política', 'Identidad, integración, recurso y acción.', 'La lectura está permitida; enviar requiere aprobación. La confianza no sustituye ninguna comprobación.', 'Lectura permitida; envío todavía no aprobado.'],
    'tool-result': ['Ejecución de herramienta', 'El sistema externo devuelve un resultado observable', 'tracking.lookup para 123456789.', 'La integración simulada responde dentro del límite.', 'Estado: delayed. Fecha confirmada: no disponible.'],
    'draft-check': ['Borrador y revisión', 'Un borrador grounded recibe una revisión falible', 'El resultado se añade al contexto de tarea.', 'Comprueba coincidencia, fecha inventada, falsa afirmación de envío e incertidumbre. No demuestra la verdad.', 'Borrador sobre retraso sin fecha inventada y sin afirmar envío.'],
    approval: ['Aprobación humana', 'Enviar exige confirmación explícita', 'Borrador grounded y política approval required.', 'La simulación no envía por defecto; el alumno puede aprobar o negar.', 'Esperando aprobación. No se envió nada.'],
    verification: ['Ejecución y verificación', 'Se verifica el resultado observable', 'Solo tras aprobación educativa: envío simulado.', 'La integración informa accepted o rejected y el producto lo compara con el objetivo.', 'Estado honesto: success, partial, waiting, blocked, denied, stopped o failed.'],
    offline: ['Feedback y evaluación', 'La mejora ocurre después y por separado', 'El feedback puede almacenarse o revisarse.', 'No todo feedback se usa. Un cambio se evalúa con casos held-out distintos.', 'Posible actualización evaluada, no aprendizaje instantáneo.'],
};

export const fullTraceLab: FullTraceLabContent = {
    ...en, sectionTitle: 'Una solicitud, varias capas, un resultado verificable', sectionIntro: 'Sigue la misma solicitud por contexto, modelo, grounding, Agent, controles, ejecución simulada y verificación.', heading: 'La traza completa', promptLabel: 'Solicitud del usuario', prompt: 'Comprueba qué ocurre con el paquete 123456789, redacta una actualización para el cliente y no la envíes sin mi aprobación.',
    disclosure: 'Simulación educativa guionizada: sin conexión real, envío real ni cadena de pensamiento oculta.', variabilityNote: 'No toda solicitud usa memoria, RAG, herramientas, Agent, aprobación, revisión o mejora offline. Puede haber saltos, repeticiones y paradas; la arquitectura varía.', layerHeading: 'Capa activa',
    layers: { model: { label: 'Model internal', description: 'Cálculo dentro del modelo' }, product: { label: 'Application or product', description: 'Contexto, orquestación y estado' }, tool: { label: 'External system or tool', description: 'Integración externa definida' }, human: { label: 'Human control', description: 'Decisión humana explícita' }, offline: { label: 'Offline improvement process', description: 'Proceso posterior separado' } },
    statusLabels: { required: 'ruta principal', optional: 'opcional', skipped: 'omitido aquí', repeated: 'puede repetirse', stop: 'punto de parada' }, labels: { input: 'Entrada', process: 'Transformación o decisión', output: 'Salida', details: 'Detalles', branchReason: 'Motivo de rama', stopReason: 'Motivo de parada', stage: 'Etapa', previous: 'Anterior', next: 'Siguiente', reset: 'Reiniciar traza', selectStage: 'Elige una etapa', progress: (c, t) => `Posición ${c} de ${t} con rutas opcionales` },
    stages: en.stages.map((s) => { const c = stageCopy[s.id]; const localized = c ? { ...s, tab: c[0], title: c[1], refresher: c[3], input: c[2], process: c[3], output: c[4], facts: undefined, details: undefined, branchReason: undefined, stopReason: undefined } : s; if (s.id === 'tokens') localized.details = { label: 'Ejemplo compacto', items: ['“comprobar” → ID 4812', '“paquete” → ID 907', '123456789 puede dividirse', 'Un ID no contiene significado'] }; if (s.id === 'representations') localized.details = { label: 'Representación compacta', items: ['4812 → [0.2, −0.4, …]', '907 → [0.7, 0.1, …]', 'Las capas transforman los vectores'] }; if (s.id === 'generation') localized.details = { label: 'Único ejemplo numérico', items: ['2.0 / 1.0 / 0.0 son logits', 'Softmax: 0.665 / 0.245 / 0.090', 'Softmax no elige', 'Decoding elige y el ciclo repite'] }; if (s.id === 'grounding-choice') localized.branchReason = 'El estado cambia con el tiempo; recuperar evidencia no modifica los parámetros.'; if (s.id === 'approval') localized.stopReason = 'El usuario exigió aprobación antes del envío.'; if (s.id === 'verification') localized.branchReason = 'Sin aprobación se omite la ejecución.'; if (s.id === 'offline') localized.branchReason = 'Es una ruta offline separada.'; return localized; }),
    branches: { ...en.branches, title: 'Explora ramas de la simulación', intro: 'La ruta puede continuar, saltar o detenerse.', missingInfo: { label: 'Falta el número', outcome: 'Preguntar en vez de inventar.' }, knowledge: { label: 'Pregunta simple', outcome: 'Puede omitir herramienta y aprobación.' }, toolNeeded: { label: 'Estado actual', outcome: 'Requiere herramienta porque cambia.' }, toolError: { label: 'Simular error', first: 'Intento 1 falló. Queda un retry.', retry: 'Retry 1 de 1 falló.', exhausted: 'Límite agotado: estado failed.' }, approval: { ...en.branches.approval, title: 'Aprobación educativa', pending: 'Esperando, no enviado', deny: 'Denegar', approve: 'Aprobar envío simulado', denied: 'Denegado: no se ejecuta.', approved: 'Aprobado solo para simulación.', accepted: 'Simular accepted', rejected: 'Simular rejected', verifyAccepted: 'Accepted verificado: success simulado.', verifyRejected: 'Rejected verificado: failed.' }, restart: 'Reiniciar rama' },
    sr: { stageGroup: 'Elegir etapa', stageDetail: 'Detalles de la etapa activa', branchGroup: 'Elegir rama educativa' },
};
