export const chapter1Quiz = {
    title: 'Knowledge check: the hidden path', subtitle: 'Five questions about product, model, and failure sources', startLabel: 'Start the quiz', submitLabel: 'Finish the quiz', completedTitle: 'You finished the quiz',
    byId: {
        1: { question: 'What does the visible chat show?', options: ['The outer request and response, but not the whole path between them', 'Every instruction and context item sent to the model', 'The exact place where every failure began', 'All internal model calculations'], explanation: 'The chat is the visible surface. It does not show everything the product and model did along the path.' },
        2: { question: 'What is the correct relationship between an AI product and the model?', options: ['The model is always the whole product', 'The product may assemble input and handle output around the model', 'The product has no role in the path', 'Every product must use a tool for every response'], explanation: 'The model is one component inside a product that may handle input and output around it.' },
        3: { question: 'Can a weak final response reveal by itself where the failure began?', options: ['Yes, it proves the model hallucinated', 'Yes, it always points to one layer', 'No, several layers can produce a similar visible result', 'No, because failures can never be investigated'], explanation: 'Different failure sources can look similar at the endpoint, so inspect the path.' },
        4: { question: 'Which statement about an unclear user request is correct?', options: ['A problem can exist in the input before model processing begins', 'The model receives the user intention directly', 'Every ambiguity is a hallucination', 'The product always fills every missing detail'], explanation: 'Ambiguous wording or a missing detail can create an input problem.' },
        5: { question: 'Which question naturally leads to Chapter 2?', options: ['What color should the send button be?', 'What exactly did the product assemble and pass as model input?', 'How can we memorize every internal stage?', 'Which tool is used in every response?'], explanation: 'The next question is what the product placed in the current model input.' },
    },
    conceptLabels: { 'הגלוי מול הנסתר': 'Visible and hidden', 'מוצר מול מודל': 'Product and model', 'מקורות כשל': 'Failure sources', 'בעיית קלט': 'Input problem', 'הגשר לפרק 2': 'Bridge to Chapter 2' } as Record<string, string>,
};
