export const chapter1Quiz = {
    title: 'Knowledge check: the hidden path', subtitle: 'Five questions about the product and the next-token path', startLabel: 'Start the quiz', submitLabel: 'Finish the quiz', completedTitle: 'You finished the quiz',
    byId: {
        1: { question: 'What does the visible chat show?', options: ['The outer request and response, but not the whole path between them', 'Every instruction and context item sent to the model', 'The exact place where every failure began', 'All internal model calculations'], explanation: 'The chat is the visible surface. It does not show everything the product and model did along the path.' },
        2: { question: 'What is the correct relationship between an AI product and the model?', options: ['The model is always the whole product', 'The product may assemble input and handle output around the model', 'The product has no role in the path', 'Every product must use a tool for every response'], explanation: 'The model is one component inside a product that may handle input and output around it.' },
        3: { question: 'Which statement about a Token ID is correct?', options: ['It is the full vector that contains the token meaning', 'Nearby IDs always represent similar meanings', 'It is a numeric vocabulary address, not meaning by itself', 'It is the probability that the token will be selected'], explanation: 'A Token ID is a stable vocabulary address. A feature-bearing numeric representation is selected later at the embedding stage.' },
        4: { question: 'What is the difference between Softmax and Decoding?', options: ['Softmax creates a probability distribution, and Decoding uses it to choose or sample a token', 'Softmax selects the final answer, and Decoding creates probabilities', 'Both verify whether the token is factually correct', 'There is no difference; they name the same computation'], explanation: 'Softmax converts logits into a distribution. Decoding applies a selection strategy to that distribution; neither is a truth check.' },
        5: { question: 'After seeing that the product may assemble input around the model, what is the next useful question?', options: ['What color should the send button be?', 'What exactly did the product assemble and pass as model input?', 'How can we memorize every internal stage?', 'Which tool is used in every response?'], explanation: 'The next question is what the product placed in the current model input.' },
    },
    conceptLabels: { 'הגלוי מול הנסתר': 'Visible and hidden', 'מוצר מול מודל': 'Product and model', 'Token ID מול משמעות': 'Token ID and meaning', 'Softmax מול Decoding': 'Softmax and Decoding', 'קלט המודל שהמוצר מרכיב': 'Product-assembled model input' } as Record<string, string>,
};
