import type { Metadata } from "next";
import { Geist, Geist_Mono, Heebo } from "next/font/google";
import "./globals.css";
import { CourseFooter } from "@/components/CourseFooter";
import { LocaleProvider } from "@/i18n/LocaleProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// גופן אחיד מבוקר (Heebo, variable) לכל הטקסט הרגיל - עברית וגם לטינית. Heebo מכסה את
// שני הכתבים ומספק משקלים אמיתיים 100-900, כך שכותרות ותיאורים, וגם מילים לועזיות כמו
// Chat / Agent בתוך משפט עברי, נראים באותו גופן. Geist נשאר רק כרשת-ביטחון (fallback),
// ו-Geist Mono נשמר בנפרד לתגים טכניים (LLM, מספרים, מזהי-טוקן) שרוצים רוחב-אותיות קבוע.
const heebo = Heebo({
  variable: "--font-hebrew",
  subsets: ["hebrew", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ברירת המחדל ב-SSR היא עברית/RTL (התנהגות נשמרת). ה-LocaleProvider מסנכרן
    // את lang/dir/data-locale על <html> אחרי mount כשנבחרת שפה אחרת (?lang=).
    // משתני הגופן (next/font) חייבים לשבת על <html>, לא על <body>: Tailwind מחיל את
    // font-family דרך var(--default-font-family) על html, וכל טקסט תוכן יורש משם. אם
    // המשתנים על body בלבד, html נופל ל-ui-sans-serif (גופן המערכת) וכל התוכן איתו.
    <html lang="he" dir="rtl" className={`${geistSans.variable} ${geistMono.variable} ${heebo.variable}`}>
      <body className="antialiased">
        <LocaleProvider>
                {children}
         <CourseFooter />
        </LocaleProvider>
      </body>
    </html>
  );
}
