import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CourseFooter } from "@/components/CourseFooter";
import { LocaleProvider } from "@/i18n/LocaleProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ברירת המחדל ב-SSR היא עברית/RTL (התנהגות נשמרת). ה-LocaleProvider מסנכרן
    // את lang/dir/data-locale על <html> אחרי mount כשנבחרת שפה אחרת (?lang=).
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocaleProvider>
                {children}
         <CourseFooter />
        </LocaleProvider>
      </body>
    </html>
  );
}
