import { fullTraceLab as en } from '../../en/behind-ai/fullTraceLab';
import type { FullTraceLabContent } from '../../he/behind-ai/fullTraceLab';

const copy: Record<string, [string, string, string]> = {
    context: ['Сборка контекста', 'Продукт собирает доступное сейчас', 'Хранилище не равно входу модели. История, сохраненная память и retention различаются; память здесь не нужна.'],
    'model-input': ['Вход модели', 'В модель входит только собранный пакет', 'Это учебное структурированное представление; формат зависит от продукта.'],
    tokens: ['Токены и ID', 'Текст превращается в токены и идентификаторы', 'Токен не всегда слово. ID является адресом, а не значением.'],
    representations: ['Embeddings', 'ID становятся изменяемыми представлениями', 'Векторы преобразуются слоями с учетом контекста, а не остаются одной фиксированной картой смысла.'],
    'attention-context': ['Attention и окно', 'Модель динамически взвешивает связи', 'Attention не является постоянным рейтингом; окно содержит доступное сейчас, а не все сохраненное.'],
    generation: ['От logits к генерации', 'Softmax создает распределение, decoding выбирает', 'Logits 2.0/1.0/0.0 дают 0.665/0.245/0.090; выбранный токен добавляется, цикл повторяется до остановки.'],
    'grounding-choice': ['Риск и grounding', 'Система решает, нужны ли текущие доказательства', 'Правдоподобный ответ может быть необоснованным; для текущего статуса выбирается инструмент.'],
    'agent-tool': ['Agent и инструмент', 'Agent является системой вокруг модели', 'Модель предлагает структурированный вызов; приложение проверяет инструмент и предел в один retry.'],
    authorization: ['Авторизация', 'Приложение проверяет authorization и policy', 'Чтение разрешено, отправка требует отдельного одобрения; уверенность не заменяет проверки.'],
    'tool-result': ['Выполнение инструмента', 'Внешняя система возвращает наблюдаемый результат', 'Для 123456789: delayed, подтвержденной даты нет; доказательство тоже может быть неполным.'],
    'draft-check': ['Черновик и проверка', 'Grounded-черновик проходит ошибочную self-check', 'Проверка не доказывает истину: дата не придумана, отправка не заявлена, неопределенность видна.'],
    approval: ['Одобрение человека', 'Отправка требует явного подтверждения', 'По умолчанию ничего не отправлено; authorization не является approval.'],
    verification: ['Выполнение и проверка', 'Наблюдаемый результат сверяется с целью', 'Accepted вызов не всегда завершает задачу; показывается честный итоговый статус.'],
    offline: ['Обратная связь и оценка', 'Улучшение происходит позже и отдельно', 'Не каждый feedback используется; обновление проверяется на отдельных held-out примерах и не означает мгновенное обучение.'],
};

export const fullTraceLab: FullTraceLabContent = {
    ...en, sectionTitle: 'Один запрос, несколько слоев, проверяемый результат', sectionIntro: 'Проследите запрос о посылке через контекст, модель, grounding, Agent, контроль, симуляцию и проверку.', heading: 'Полная трассировка', promptLabel: 'Запрос пользователя', prompt: 'Проверь посылку 123456789, составь обновление для клиента и не отправляй без моего одобрения.', disclosure: 'Это сценарная учебная симуляция без реального подключения, отправки и скрытой цепочки рассуждений.', variabilityNote: 'Не каждый запрос использует память, RAG, инструменты, Agent, approval, self-check или offline-улучшение. Этапы могут пропускаться, повторяться и останавливаться.', layerHeading: 'Активный слой',
    layers: { model: { label: 'Model internal', description: 'Вычисление внутри модели' }, product: { label: 'Application or product', description: 'Контекст, оркестрация и состояние' }, tool: { label: 'External system or tool', description: 'Определенная внешняя интеграция' }, human: { label: 'Human control', description: 'Явное решение человека' }, offline: { label: 'Offline improvement process', description: 'Отдельный более поздний процесс' } }, statusLabels: { required: 'главный путь', optional: 'необязательно', skipped: 'пропущено', repeated: 'может повторяться', stop: 'точка остановки' }, labels: { input: 'Вход', process: 'Преобразование или решение', output: 'Выход', details: 'Подробности', branchReason: 'Причина ветки', stopReason: 'Причина остановки', stage: 'Этап', previous: 'Назад', next: 'Далее', reset: 'Сбросить', selectStage: 'Выберите этап', progress: (c, t) => `Позиция ${c} из ${t}, есть необязательные пути` },
    stages: en.stages.map((s) => { const c = copy[s.id]; const localized = c ? { ...s, tab: c[0], title: c[1], refresher: c[2], input: c[2], process: c[2], output: c[2], facts: undefined, details: undefined, branchReason: undefined, stopReason: undefined } : s; if (s.id === 'tokens') localized.details = { label: 'Короткий пример', items: ['«проверить» → ID 4812', '«посылка» → ID 907', 'Номер может делиться на токены', 'ID сам по себе не содержит смысла'] }; if (s.id === 'representations') localized.details = { label: 'Короткое представление', items: ['4812 → [0.2, −0.4, …]', '907 → [0.7, 0.1, …]', 'Слои преобразуют векторы'] }; if (s.id === 'generation') localized.details = { label: 'Единственный числовой пример', items: ['2.0 / 1.0 / 0.0 это logits', 'Softmax: 0.665 / 0.245 / 0.090', 'Softmax не выбирает', 'Decoding выбирает, цикл повторяется'] }; if (s.id === 'grounding-choice') localized.branchReason = 'Статус меняется; retrieval добавляет доказательство, не меняя параметры.'; if (s.id === 'approval') localized.stopReason = 'Пользователь потребовал approval до отправки.'; if (s.id === 'verification') localized.branchReason = 'Без approval выполнение пропускается.'; if (s.id === 'offline') localized.branchReason = 'Это отдельный offline-путь.'; return localized; }),
    branches: { ...en.branches, title: 'Исследуйте ветви симуляции', intro: 'Путь может продолжиться, пропуститься или остановиться.', missingInfo: { label: 'Нет номера', outcome: 'Спросить, не выдумывать.' }, knowledge: { label: 'Простой вопрос', outcome: 'Инструмент и approval можно пропустить.' }, toolNeeded: { label: 'Текущий статус', outcome: 'Нужен инструмент.' }, toolError: { label: 'Ошибка инструмента', first: 'Попытка 1 неудачна. Остался один retry.', retry: 'Retry 1 из 1 неудачен.', exhausted: 'Предел исчерпан: failed.' }, approval: { ...en.branches.approval, title: 'Учебное approval', pending: 'Ожидание, не отправлено', deny: 'Отклонить', approve: 'Одобрить симуляцию', denied: 'Отклонено, выполнения нет.', approved: 'Одобрено только для симуляции.', accepted: 'Симулировать accepted', rejected: 'Симулировать rejected', verifyAccepted: 'Accepted проверен: симулированный success.', verifyRejected: 'Rejected проверен: failed.' }, restart: 'Перезапустить ветку' }, sr: { stageGroup: 'Выбор этапа', stageDetail: 'Активный этап', branchGroup: 'Выбор учебной ветки' },
};
