import { fullTraceLab as en } from '../../en/behind-ai/fullTraceLab';
import type { FullTraceLabContent } from '../../he/behind-ai/fullTraceLab';

const copy: Record<string, [string, string, string, string, string, string]> = {
    context: ['コンテキストの組み立て', 'プロダクトが今使える情報を集める', '保存とモデル入力は別です。現在の文脈、履歴、保存メモリ、retentionを区別し、この例ではメモリを取得しません。', 'ユーザーの依頼と現在の会話状態。', 'プロダクトは関連するシステムルールを追加し、会話履歴、保存メモリ、retentionを区別します。メモリは取得され得ますが、retentionは保存ポリシーにすぎません。', '組み立てられた現在のコンテキスト。この例では保存メモリは不要で、事前のツール結果もありません。'],
    'model-input': ['モデル入力', '組み立てたパッケージだけがモデルに入る', '教育用の簡略表現であり、実装形式はプロダクトごとに異なります。', 'システムルール、ユーザーの目標、制約、選択されたコンテキスト。', 'プロダクトは隠れたpromptを見せずにシンプルな構造化パッケージを作成します。', 'System: 現在の根拠を使い、承認なしに送信しない。Goal: 荷物を確認し更新を作成。Known: 123456789。Missing: 状況と日付。Sources: まだなし。'],
    tokens: ['Tokens と IDs', 'テキストをトークンと識別子に変える', 'トークンは単語とは限らず、ID自体に意味はありません。', '抜粋:「確認 … 荷物123456789」。', 'tokenizerがテキストを断片に分け、各断片をIDに対応付けます。', '数値IDの並び。'],
    representations: ['Embeddings', 'IDを変換可能な表現にする', 'ベクトルは文脈に応じて層で変換され、固定された意味の地図ではありません。', 'token ID。', 'IDはベクトルに対応付けられ、層が文脈と意味関係に応じてそれを変換します。', '荷物、確認、顧客、承認制約を結び付ける文脈表現。'],
    'attention-context': ['Attention と window', '現在の窓の関係を動的に重み付けする', 'Attentionは永久順位ではなく、context windowは過去に保存された全情報ではありません。', '表現と、現在context windowにある情報。', '今のところ「送信しない」は「承認」と強く関連しますが、別のステップでは重みが変わり得ます。', '次のtoken予測のための更新された表現。'],
    generation: ['Logits から生成', 'Softmaxが分布を作りdecodingが選ぶ', 'logits 2.0/1.0/0.0から0.665/0.245/0.090。選択トークンを追加し停止条件まで繰り返します。', '更新された表現。', 'logits:「確認済み」2.0、「送信済み」1.0、「明日」0.0。softmax: 0.665、0.245、0.090、合計1.000。decodingが「確認済み」を選びます。', '「確認済み」が追加され、停止token、長さ上限、システム停止のいずれかまで予測が繰り返されます。'],
    'grounding-choice': ['リスクとgrounding', '最新の根拠が必要か判断する', 'もっともらしい文でも根拠不足になり得ます。現在の配送状況にはツールを使い、単純な知識質問なら省略できます。', 'タスクは荷物の最新事実を求めています。', '根拠なしの経路はここでは使いません。単純な知識質問ならツールを省略できることもあります。', '構造化されたtool call提案を要求します。'],
    'agent-tool': ['Agent とツール', 'Agentはモデルを囲むプロダクトシステム', 'モデルは構造化呼び出しを提案でき、アプリが利用可否と上限一回のretryを判断します。', 'Goal、制約、task state、そしてtracking.lookupの提案。', 'モデルは構造化された呼び出しを提案でき、アプリが利用可否と適合性を確認します。task stateは長期記憶ではありません。', 'Tool: tracking.lookup。Input: { trackingNumber: 「123456789」}。Expected: 状況と確定日。'],
    authorization: ['Authorization', 'アプリが権限とpolicyを確認する', '追跡の読み取りは許可、送信は別のapprovalが必要です。confidenceはどちらも上書きしません。', 'identity、integration、リソース、要求された操作。', '追跡の読み取りは許可されます。今後の送信には別途approvalが必要です。人のapprovalはpolicyでブロックされた操作を解除できません。', '追跡の読み取りは許可、送信はまだ未承認。'],
    'tool-result': ['ツール実行', '外部システムが観測可能な結果を返す', '123456789はdelayed、確定到着日はなし。外部根拠も不完全な場合があります。', 'tracking.lookup({ trackingNumber: 「123456789」})。', '台本化されたintegrationが試行上限内で応答します。', 'status: delayed。confirmedArrivalDate: unavailable。'],
    'draft-check': ['下書きと確認', 'groundedな下書きを誤り得るself-checkで確認', '日付の捏造、送信済みの主張、不確実性を確認しますが、真実の証明ではありません。', 'ツール結果が現在のtask contextに追加されます。', '確認: delayedと一致✓、日付を捏造していない✓、送信済みと主張していない✓、不確実性が明示✓。', '「荷物123456789を確認しました。追跡によると遅延しており、確定した到着日はまだありません。情報が入り次第お知らせします。」'],
    approval: ['人の承認', '送信には明示的な確認が必要', '既定では送信しません。システムauthorizationと人のapprovalは別です。', '根拠のある下書き。policyはapproval requiredとしています。', 'デモは既定で送信しません。学習者は教育用のapproveまたはdeny分岐を選べます。', '承認待ち。何も送信されていません。'],
    verification: ['実行と検証', '観測結果をユーザー目標と照合する', 'ツールacceptedだけでタスク完了とは限らず、正直な最終状態を表示します。', '教育用approvalの後のみ: 下書きでsendMessage。', '台本化されたintegrationがacceptedまたはrejectedを報告し、プロダクトがその結果を目標と照合します。', '正直な状態: success、partial、waiting、blocked、denied、stopped、failedのいずれか。'],
    offline: ['フィードバックと評価', '改善は後で別経路で行う', '全feedbackが使われるわけではなく、更新は別のheld-out事例で評価され、一会話で即時学習しません。', 'フィードバックは送信、保存、レビューされることがあります。', 'すべてのフィードバックが選ばれるわけではありません。適した例はprompt、ルール、workflow、retrieval source、モデルの更新に使われることがあります。更新は別のheld-out事例で評価されます。', '評価を経た可能性のある更新であり、この会話からの即時学習ではありません。'],
};

export const fullTraceLab: FullTraceLabContent = {
    ...en, sectionTitle: '1つの依頼、複数の層、検証できる結果', sectionIntro: '同じ荷物依頼をcontext、モデル、grounding、Agent、制御、模擬実行、検証まで追跡します。', heading: 'フルトレース', promptLabel: 'ユーザーの依頼', prompt: '荷物123456789の状況を確認し、顧客向け更新を作成してください。私の承認なしに送信しないでください。', disclosure: '台本化された教育シミュレーションです。実接続、実送信、隠れた思考連鎖の表示はありません。', variabilityNote: 'すべての依頼がmemory、RAG、tool、Agent、approval、self-check、offline改善を使うわけではありません。省略、反復、早期停止があり、構成も製品ごとに異なります。', layerHeading: '現在のレイヤー',
    layers: { model: { label: 'モデル内部', description: 'モデル内部の計算' }, product: { label: 'アプリケーションまたはプロダクト', description: '組み立て、調整、task state' }, tool: { label: '外部システムまたはツール', description: '定義された外部連携' }, human: { label: '人による制御', description: '明示的な人の判断' }, offline: { label: 'オフライン改善プロセス', description: 'ライブ応答外の後工程' } }, statusLabels: { required: '主経路', optional: '任意', skipped: 'この例では省略', repeated: '反復あり', stop: '停止点' }, labels: { input: '入力', process: '変換または判断', output: '出力', details: '詳細', branchReason: '分岐理由', stopReason: '停止理由', stage: '段階', previous: '前へ', next: '次へ', reset: 'リセット', selectStage: '主要段階を選択', progress: (c, t) => `任意経路を含む ${t} 段階中 ${c}` },
    stages: en.stages.map((s) => { const c = copy[s.id]; const localized = c ? { ...s, tab: c[0], title: c[1], refresher: c[2], input: c[3], process: c[4], output: c[5], facts: undefined, details: undefined, branchReason: undefined, stopReason: undefined } : s; if (s.id === 'tokens') localized.details = { label: '短い例', items: ['「確認」→ ID 4812', '「荷物」→ ID 907', '番号は複数tokenになり得る', 'ID自体に意味はない'] }; if (s.id === 'representations') localized.details = { label: '短い表現', items: ['4812 → [0.2, −0.4, …]', '907 → [0.7, 0.1, …]', '層がベクトルを変換する'] }; if (s.id === 'generation') localized.details = { label: '唯一の数値例', items: ['2.0 / 1.0 / 0.0 はlogits', 'Softmax: 0.665 / 0.245 / 0.090', 'Softmaxは選択しない', 'Decodingが選びloopを繰り返す'] }; if (s.id === 'grounding-choice') localized.branchReason = '状態は変化するため根拠を取得しますが、モデルパラメータは変わりません。'; if (s.id === 'approval') localized.stopReason = 'ユーザーが送信前の承認を明示しました。'; if (s.id === 'verification') localized.branchReason = 'approvalがなければ実行を省略します。'; if (s.id === 'offline') localized.branchReason = 'ライブ応答とは別のoffline経路です。'; return localized; }),
    branches: { ...en.branches, title: 'シミュレーション分岐を試す', intro: '経路が継続、省略、停止する理由を確認します。', missingInfo: { label: '追跡番号がない', outcome: '捏造せずユーザーに質問。' }, knowledge: { label: '単純な知識質問', outcome: 'ツールとapprovalを省略可能。' }, toolNeeded: { label: '現在の配送状況', outcome: '変化するためツールが必要。' }, toolError: { label: 'ツールエラー', first: '試行1失敗。retryは残り1回。', retry: 'retry 1/1失敗。', exhausted: '上限到達: failed。' }, approval: { ...en.branches.approval, title: '教育用approval', pending: '待機中、未送信', deny: '送信を拒否', approve: '模擬送信を承認', denied: '拒否。実行なし。', approved: 'シミュレーションのみ承認。', accepted: 'acceptedを模擬', rejected: 'rejectedを模擬', verifyAccepted: 'acceptedを検証: 模擬success。', verifyRejected: 'rejectedを検証: failed。' }, restart: '分岐を戻す' }, sr: { stageGroup: '段階を選択', stageDetail: '現在の段階の詳細', branchGroup: '教育用分岐を選択' },
};
